---------PROJEKT 
---------BAZA DANYCH "SIEC PIZZERII" 
---------MICHAL KACZYNSKI 
---------H6X1S1
---------SKRYPT ORACLE INSTALACJA





--TWORZENIE TABEL
CREATE TABLE faktura_detale (
    pozycja       NUMBER(6) NOT NULL,
    id_faktury    NUMBER(6) NOT NULL,
    liczba        NUMBER(3) NOT NULL,
    cena_zakupu   NUMBER(5,2) NOT NULL,
    id_produktu   NUMBER(4) NOT NULL
);

ALTER TABLE faktura_detale ADD CONSTRAINT faktura_detale_pk PRIMARY KEY ( pozycja,id_faktury );

CREATE TABLE faktura_naglowek (
    id_faktury        NUMBER(6) NOT NULL,
    data_faktury      DATE NOT NULL,
    wartosc_faktury   NUMBER(7,2) NOT NULL,
    id_klienta        NUMBER(5) NOT NULL,
    id_lokalu         NUMBER(3) NOT NULL,
    id_samochodu      NUMBER(5),
    id_platnosci      NUMBER(2) NOT NULL,
    id_pracownika     NUMBER(5) NOT NULL
);

ALTER TABLE faktura_naglowek ADD CONSTRAINT faktura_naglowek_pk PRIMARY KEY ( id_faktury );

CREATE TABLE kierownik (
    id_kierownika   NUMBER(5) NOT NULL,
    imie            VARCHAR2(20) NOT NULL,
    nazwisko        VARCHAR2(50) NOT NULL
);

ALTER TABLE kierownik ADD CONSTRAINT kierownik_pk PRIMARY KEY ( id_kierownika );

CREATE TABLE klient (
    id_klienta   NUMBER(5) NOT NULL,
    adres        VARCHAR2(100),
    telefon      NUMBER(9)
);

ALTER TABLE klient ADD CONSTRAINT klient_pk PRIMARY KEY ( id_klienta );

CREATE TABLE lokal (
    id_lokalu        NUMBER(3) NOT NULL,
    nazwa_lokalu     VARCHAR2(50) NOT NULL,
    telefon          NUMBER(9) NOT NULL,
    adres            VARCHAR2(100) NOT NULL,
    id_wojewodztwa   NUMBER(4) NOT NULL,
    id_kierownika    NUMBER(5) NOT NULL,
	koszt NUMBER(6) NOT NULL
);

ALTER TABLE lokal ADD CONSTRAINT lokal_pk PRIMARY KEY ( id_lokalu );

CREATE TABLE pracownik (
    id_pracownika   NUMBER(5) NOT NULL,
    imie            VARCHAR2(30) NOT NULL,
    nazwisko        VARCHAR2(50) NOT NULL,
    id_lokalu       NUMBER(3) NOT NULL
);

ALTER TABLE pracownik ADD CONSTRAINT pracownik_pk PRIMARY KEY ( id_pracownika );

CREATE TABLE produkt (
    id_produktu      NUMBER(4) NOT NULL,
    nazwa_produktu   VARCHAR2(100) NOT NULL,
    id_lokalu        NUMBER(3) NOT NULL,
    cena_produktu    NUMBER(5,2) NOT NULL
);

ALTER TABLE produkt ADD CONSTRAINT produkt_pk PRIMARY KEY ( id_produktu );

CREATE TABLE samochod (
    id_samochodu      NUMBER(5) NOT NULL,
    nazwa_samochodu   VARCHAR2(70) NOT NULL,
    id_lokalu         NUMBER(3) NOT NULL
);

ALTER TABLE samochod ADD CONSTRAINT samochod_pk PRIMARY KEY ( id_samochodu );

CREATE TABLE sposob_platnosci (
    id_platnosci      NUMBER(2) NOT NULL,
    nazwa_platnosci   VARCHAR2(50) NOT NULL
);

ALTER TABLE sposob_platnosci ADD CONSTRAINT sposob_platnosci_pk PRIMARY KEY ( id_platnosci );

CREATE TABLE wojewodztwo (
    id_wojewodztwa      NUMBER(4) NOT NULL,
    nazwa_wojewodztwa   VARCHAR2(50) NOT NULL
);

ALTER TABLE wojewodztwo ADD CONSTRAINT wojewodztwo_pk PRIMARY KEY ( id_wojewodztwa );

CREATE TABLE wyposazenie (
    id_wyposazenia      NUMBER(6) NOT NULL,
    nazwa_wyposazenia   VARCHAR2(100) NOT NULL,
    id_lokalu           NUMBER(3) NOT NULL
);

ALTER TABLE wyposazenie ADD CONSTRAINT wyposazenie_pk PRIMARY KEY ( id_wyposazenia );
 
ALTER TABLE faktura_detale
    ADD CONSTRAINT faktura_detale_faktura_naglowek_fk FOREIGN KEY ( id_faktury )
        REFERENCES faktura_naglowek ( id_faktury );

ALTER TABLE faktura_detale
    ADD CONSTRAINT faktura_detale_produkt_fk FOREIGN KEY ( id_produktu )
        REFERENCES produkt ( id_produktu );

ALTER TABLE faktura_naglowek
    ADD CONSTRAINT faktura_naglowek_klient_fk FOREIGN KEY ( id_klienta )
        REFERENCES klient ( id_klienta );

ALTER TABLE faktura_naglowek
    ADD CONSTRAINT faktura_naglowek_lokal_fk FOREIGN KEY ( id_lokalu )
        REFERENCES lokal ( id_lokalu );

ALTER TABLE faktura_naglowek
    ADD CONSTRAINT faktura_naglowek_pracownik_fk FOREIGN KEY ( id_pracownika )
        REFERENCES pracownik ( id_pracownika );

ALTER TABLE faktura_naglowek
    ADD CONSTRAINT faktura_naglowek_samochod_fk FOREIGN KEY ( id_samochodu )
        REFERENCES samochod ( id_samochodu );

ALTER TABLE faktura_naglowek
    ADD CONSTRAINT faktura_naglowek_sposob_platnosci_fk FOREIGN KEY ( id_platnosci )
        REFERENCES sposob_platnosci ( id_platnosci );

ALTER TABLE lokal
    ADD CONSTRAINT lokal_kierownik_fk FOREIGN KEY ( id_kierownika )
        REFERENCES kierownik ( id_kierownika );

ALTER TABLE lokal
    ADD CONSTRAINT lokal_wojewodztwo_fk FOREIGN KEY ( id_wojewodztwa )
        REFERENCES wojewodztwo ( id_wojewodztwa );

ALTER TABLE pracownik
    ADD CONSTRAINT pracownik_lokal_fk FOREIGN KEY ( id_lokalu )
        REFERENCES lokal ( id_lokalu );

ALTER TABLE produkt
    ADD CONSTRAINT produkt_lokal_fk FOREIGN KEY ( id_lokalu )
        REFERENCES lokal ( id_lokalu );

ALTER TABLE samochod
    ADD CONSTRAINT samochod_lokal_fk FOREIGN KEY ( id_lokalu )
        REFERENCES lokal ( id_lokalu );

ALTER TABLE wyposazenie
    ADD CONSTRAINT wyposazenie_lokal_fk FOREIGN KEY ( id_lokalu )
        REFERENCES lokal ( id_lokalu );




----------------SEKWENCJA SEQ_KIEROWNIK

--TWORZENIE SEQ_KIEROWNIK
CREATE SEQUENCE SEQ_KIEROWNIK INCREMENT BY 1 START WITH 1 MAXVALUE 999 MINVALUE 1;

----------------SEKWENCJA SEQ_KLIENT

--TWORZENIE SEQ_KLIENT
CREATE SEQUENCE SEQ_KLIENT INCREMENT BY 1 START WITH 1 MAXVALUE 999 MINVALUE 1;

----------------SEKWENCJA SEQ_LOKAL

--TWORZENIE SEQ_LOKAL
CREATE SEQUENCE SEQ_LOKAL INCREMENT BY 1 START WITH 1 MAXVALUE 999 MINVALUE 1;

----------------SEKWENCJA SEQ_SAMOCHOD

--TWORZENIE SEQ_SAMOCHOD
CREATE SEQUENCE SEQ_SAMOCHOD INCREMENT BY 1 START WITH 1 MAXVALUE 999 MINVALUE 1;

----------------SEKWENCJA SEQ_PRODUKT

--TWORZENIE SEQ_PRODUKT
CREATE SEQUENCE SEQ_PRODUKT INCREMENT BY 1 START WITH 1 MAXVALUE 999 MINVALUE 1;

----------------SEKWENCJA SEQ_PRACOWNIK

--TWORZENIE SEQ_PRACOWNIK
CREATE SEQUENCE SEQ_PRACOWNIK INCREMENT BY 1 START WITH 1 MAXVALUE 999 MINVALUE 1;

----------------SEKWENCJA SEQ_WYPOSAZENIE

--TWORZENIE SEQ_WYPOSAZENIE
CREATE SEQUENCE SEQ_WYPOSAZENIE INCREMENT BY 1 START WITH 1 MAXVALUE 999 MINVALUE 1;

----------------SEKWENCJA SEQ_FAKTURA_NAGLOWEK

--TWORZENIE SEQ_FAKTURA_NAGLOWEK
CREATE SEQUENCE SEQ_FAKTURA_NAGLOWEK INCREMENT BY 1 START WITH 1 MAXVALUE 9999 MINVALUE 1;

--TWORZENIE SEQ_FAKTURA_DETALE
CREATE SEQUENCE SEQ_FAKTURA_DETALE INCREMENT BY 1 START WITH 1 MAXVALUE 9999 MINVALUE 1;








--WSTAWIANIE DO TABELI KIEROWNIK
INSERT INTO KIEROWNIK VALUES(SEQ_KIEROWNIK.NEXTVAL,'Michal','Kaczynski'); 
INSERT INTO KIEROWNIK VALUES(SEQ_KIEROWNIK.NEXTVAL,'Anna','Zakrzewska'); 
INSERT INTO KIEROWNIK VALUES(SEQ_KIEROWNIK.NEXTVAL,'Tymoteusz','Michalski'); 
INSERT INTO KIEROWNIK VALUES(SEQ_KIEROWNIK.NEXTVAL,'Bartek','Ma³ecki'); 
INSERT INTO KIEROWNIK VALUES(SEQ_KIEROWNIK.NEXTVAL,'Maria','Soko³owska'); 
--ILOSC DANYCH: 5



--WSTAWIANIE DO TABELI KLIENT
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'ul. Jana Paw³a 136/35, Ostro³êka',783157643);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'ul. Okopowa 36/23, Warszawa',881975215);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'ul. Marsza³kowska 5/8, Warszawa',734381160);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'ul. Antoniny 3/7, Warszawa',536305617);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'ul. Sienkiewicza 1/22, Ostro³êka',788028614);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'ul. Koœciuszki 11/54, Warszawa',690335623);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'ul. Brzechwy 30, Warszawa',661776872);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'ul. Rydzowa 2/21, Warszawa',789097880);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'ul. 11 listopada 9/33, Ostro³êka',737550625);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'ul. S³oneczna 9/245, Kraków',721292745);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'ul. Kreta 24/2, Kraków',783764266);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'ul. Skryta 7/75, Warszawa',571201828);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'ul. Brzozowa 3/64, Warszawa',690635678);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'ul. Bohaterów Westerplatte 3/2, Warszawa',699286170);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'ul. Mickiewicza 6/35, Kraków',739399410);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'ul. Zachodnia 62/5, Kraków',734488596);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'ul. Zachodnia 62/6, Kraków',699092265);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'ul. ¯eromskiego 3/23, Warszawa',737651582);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'ul. Fabryczna 5/2, Krakow',880457665);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'ul. Gajowa 9/9, Ostro³êka',795535633);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'ul. Kopernika 6/64, Ostro³êka',536825242);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'ul. Myœliwska 73/222, Kraków',699620090);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'ul. M³ynarska 1/16, Warszawa',727359525);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'al. Jerozolimskie 57/2, Warszawa',884321689);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'al. Jerozolimskie 57/3, Warszawa',789757708);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,'al. Solidarnoœci 4/9, Warszawa',789239423);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
INSERT INTO KLIENT VALUES(SEQ_KLIENT.NEXTVAL,NULL,NULL);
--ILOSC DANYCH: 70



--WSTAWIANIE DO TABELI WOJEWODZTWO 
INSERT INTO WOJEWODZTWO VALUES(1,'Dolnoœl¹skie');
INSERT INTO WOJEWODZTWO VALUES(2,'Kujawsko-pomorskie');
INSERT INTO WOJEWODZTWO VALUES(3,'Lubelskie');
INSERT INTO WOJEWODZTWO VALUES(4,'Lubuskie');
INSERT INTO WOJEWODZTWO VALUES(5,'?dzkie');
INSERT INTO WOJEWODZTWO VALUES(6,'Ma³opolskie');
INSERT INTO WOJEWODZTWO VALUES(7,'Mazowieckie');
INSERT INTO WOJEWODZTWO VALUES(8,'Opolskie');
INSERT INTO WOJEWODZTWO VALUES(9,'Podkarpackie');
INSERT INTO WOJEWODZTWO VALUES(10,'Podlaskie');
INSERT INTO WOJEWODZTWO VALUES(11,'Pomorskie');
INSERT INTO WOJEWODZTWO VALUES(12,'Œl¹skie');
INSERT INTO WOJEWODZTWO VALUES(13,'Œwiêtokrzyskie');
INSERT INTO WOJEWODZTWO VALUES(14,'Warmiñsko-mazurskie');
INSERT INTO WOJEWODZTWO VALUES(15,'Wielkopolskie');
INSERT INTO WOJEWODZTWO VALUES(16,'Zachodniopomorskie');
--ILOSC DANYCH: 16



--WSTAWIANIE DO TABELI LOKAL
INSERT INTO LOKAL VALUES(SEQ_LOKAL.NEXTVAL,'BazaPizzy Warszawa',727184135,'ul. Marsza³kowska 3/6',7,1,4000);
INSERT INTO LOKAL VALUES(SEQ_LOKAL.NEXTVAL,'BazaPizzy Warszawa',786212051,'ul. Wolska 42/3',7,1,2000);
INSERT INTO LOKAL VALUES(SEQ_LOKAL.NEXTVAL,'BazaPizzy Warszawa',787423893,'ul. Górczewska 9/3',7,1,3000);
INSERT INTO LOKAL VALUES(SEQ_LOKAL.NEXTVAL,'BazaPizzy Ostroleka',727250840,'ul. Jana Paw³a 78/24',7,2,6000);
INSERT INTO LOKAL VALUES(SEQ_LOKAL.NEXTVAL,'BazaPizzy Krakow',794975472,'ul. Myœliwska 8/4',6,3,3500);
INSERT INTO LOKAL VALUES(SEQ_LOKAL.NEXTVAL,'BazaPizzy Ostroleka',699135914,'ul. Józefa Bema 1/92',7,4,4000);
INSERT INTO LOKAL VALUES(SEQ_LOKAL.NEXTVAL,'BazaPizzy Krakow',729136015,'ul. Zachodnia 28/17',6,5,4000);
--ILOSC DANYCH: 7


--WSTAWIANIE DO TABELI SAMOCHOD
INSERT INTO SAMOCHOD VALUES (SEQ_SAMOCHOD.NEXTVAL,'Fiat Cinquecento Happy 1995r.',1);
INSERT INTO SAMOCHOD VALUES (SEQ_SAMOCHOD.NEXTVAL,'Fiat Panda II 1.4 2006r.',1);
INSERT INTO SAMOCHOD VALUES (SEQ_SAMOCHOD.NEXTVAL,'Fiat Panda II 1.4 2006r.',1);
INSERT INTO SAMOCHOD VALUES (SEQ_SAMOCHOD.NEXTVAL,'Fiat Panda II 1.4 2006r.',2);
INSERT INTO SAMOCHOD VALUES (SEQ_SAMOCHOD.NEXTVAL,'Fiat Panda II 1.4 2006r.',3);
INSERT INTO SAMOCHOD VALUES (SEQ_SAMOCHOD.NEXTVAL,'Fiat Panda II 1.4 2006r.',4);
INSERT INTO SAMOCHOD VALUES (SEQ_SAMOCHOD.NEXTVAL,'Fiat Panda II 1.4 2007r.',5);
INSERT INTO SAMOCHOD VALUES (SEQ_SAMOCHOD.NEXTVAL,'Fiat Panda II 1.4 2006r.',6);
INSERT INTO SAMOCHOD VALUES (SEQ_SAMOCHOD.NEXTVAL,'Fiat Panda II 1.4 2006r.',5);
INSERT INTO SAMOCHOD VALUES (SEQ_SAMOCHOD.NEXTVAL,'Fiat Panda II 1.4 2006r.',7);
--ILOSC DANYCH: 10



--WSTAWIANIE DO TABELI SPOSOB_PLATNOSCI
INSERT INTO SPOSOB_PLATNOSCI VALUES (1,'Gotówka');
INSERT INTO SPOSOB_PLATNOSCI VALUES (2,'Karta p³atnicza');
INSERT INTO SPOSOB_PLATNOSCI VALUES (3,'PayU - op³ata online');
INSERT INTO SPOSOB_PLATNOSCI VALUES (4,'Bitcoin');
--ILOSC DANYCH: 4


--WSTAWIANIE DO TABELI PRODUKT
--ID LOKALU:1
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Margherita',1,16.50);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Firestarter',1,19.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Pepperone',1,19.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Vesuvio',1,17.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Roma',1,19.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Capricciosa',1,17.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Ricco',1,19.50);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Becon',1,18.50);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Strong',1,20.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Mexicana',1,25.00);
--ID LOKALU: 2
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Margherita',2,16.50);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Firestarter',2,19.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Pepperone',2,19.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Vesuvio',2,17.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Roma',2,19.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Capricciosa',2,17.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Ricco',2,19.50);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Becon',2,18.50);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Strong',2,20.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Mexicana',2,25.00);
--ID LOKALU: 3
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Margherita',3,16.50);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Firestarter',3,19.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Pepperone',3,19.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Vesuvio',3,17.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Roma',3,19.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Capricciosa',3,17.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Ricco',3,19.50);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Becon',3,18.50);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Strong',3,20.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Mexicana',3,25.00);
--ID LOKALU: 4
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Margherita',4,16.50);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Firestarter',4,19.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Pepperone',4,19.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Vesuvio',4,17.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Roma',4,19.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Capricciosa',4,17.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Ricco',4,19.50);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Becon',4,18.50);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Strong',4,20.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Mexicana',4,25.00);
--ID LOKALU: 5
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Margherita',5,16.50);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Firestarter',5,19.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Pepperone',5,19.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Vesuvio',5,17.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Roma',5,19.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Capricciosa',5,17.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Ricco',5,19.50);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Becon',5,18.50);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Strong',5,20.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Mexicana',5,25.00);
--ID LOKALU: 6
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Margherita',6,16.50);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Firestarter',6,19.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Pepperone',6,19.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Vesuvio',6,17.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Roma',6,19.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Capricciosa',6,17.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Ricco',6,19.50);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Becon',6,18.50);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Strong',6,20.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Mexicana',6,25.00);
--ID LOKALU: 7
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Margherita',7,16.50);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Firestarter',7,19.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Pepperone',7,19.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Vesuvio',7,17.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Roma',7,19.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Capricciosa',7,17.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Ricco',7,19.50);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Becon',7,18.50);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Strong',7,20.00);
INSERT INTO PRODUKT VALUES (SEQ_PRODUKT.NEXTVAL,'Mexicana',7,25.00);
--ILOSC DANYCH: 70





--WSTAWIANIE DO TABELI PRACOWNIK
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Oliwia','Mazur',1);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Natalia','Kamiñska',1);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Krzysztof','Baranowski',1);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Damian','Jankowski',1);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Natalia','Zaj¹c',1);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Zofia','Lewandowska',2);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Patryk','Zych',2);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'£ukasz','Zalewski',2);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Marcel','Zakrzewski',2);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Jagoda','Nowicka',2);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Mateusz','Pietrzak',3);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Gabriel','Nowak',3);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Boles³aw','Olszewski',3);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Maja','Kurek',3);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Lena','Makowska',3);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'£ukasz','Markiewicz',4);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Sara','Wiœniewska',4);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Patrycja','Nowak',4);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Tymon','Olejnik',4);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Oliwia','Wiœniewska',4);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Maja','Maciejewska',5);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Julia','Wojciechowska',5);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Antonina','Tomaszewska',5);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Emilia','Kozie³',5);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Zofia','Kowalczyk',5);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Mateusz','B¹k',6);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Sara','Wolska',6);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Jerzy','Szewczyk',6);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Monika','Sobczyk',6);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Natalia','Pawlik',6);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Jakub','Wysocki',7);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Micha³','Kaczmarek',7);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Zofia','Owczarek',7);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Maja','Polak',7);
INSERT INTO PRACOWNIK VALUES (SEQ_PRACOWNIK.NEXTVAL,'Oliwia','Baran',7);
--ILOSC DANYCH: 35




--WSTAWIANIE DO TABELI WYPOSAZENIE
--LOKAL1
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Piec kamienny PIECEX',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Piec kamienny PIECEX',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Patelnia TEFAL',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Patelnia TEFAL',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Widelcow x50',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Widelcow x50',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Widelcow x50',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Nozy x50',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Nozy x50',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Nozy x50',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿ek x50',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿ek x50',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿ek x50',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿eczek x50',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿eczek x50',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿eczek x50',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Talerzy x50',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Talerzy x50',1);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Talerzy x50',1);
--LOKAL2
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Piec kamienny PIECEX',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Piec kamienny PIECEX',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Patelnia TEFAL',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Patelnia TEFAL',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Widelcow x50',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Widelcow x50',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Widelcow x50',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Nozy x50',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Nozy x50',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Nozy x50',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿ek x50',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿ek x50',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿ek x50',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿eczek x50',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿eczek x50',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿eczek x50',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Talerzy x50',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Talerzy x50',2);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Talerzy x50',2);
--LOKAL3
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Piec kamienny PIECEX',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Piec kamienny PIECEX',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Patelnia TEFAL',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Patelnia TEFAL',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Widelcow x50',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Widelcow x50',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Widelcow x50',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Nozy x50',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Nozy x50',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Nozy x50',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿ek x50',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿ek x50',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿ek x50',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿eczek x50',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿eczek x50',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿eczek x50',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Talerzy x50',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Talerzy x50',3);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Talerzy x50',3);
--LOKAL4
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Piec kamienny PIECEX',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Piec kamienny PIECEX',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Patelnia TEFAL',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Patelnia TEFAL',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Widelcow x50',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Widelcow x50',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Widelcow x50',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Nozy x50',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Nozy x50',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Nozy x50',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿ek x50',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿ek x50',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿ek x50',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿eczek x50',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿eczek x50',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿eczek x50',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Talerzy x50',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Talerzy x50',4);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Talerzy x50',4);
--LOKAL5
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Piec kamienny PIECEX',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Piec kamienny PIECEX',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Patelnia TEFAL',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Patelnia TEFAL',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Widelcow x50',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Widelcow x50',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Widelcow x50',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Nozy x50',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Nozy x50',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Nozy x50',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿ek x50',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿ek x50',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿ek x50',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿eczek x50',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿eczek x50',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿eczek x50',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Talerzy x50',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Talerzy x50',5);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Talerzy x50',5);
--LOKAL6
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Piec kamienny PIECEX',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Piec kamienny PIECEX',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Patelnia TEFAL',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Patelnia TEFAL',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Widelcow x50',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Widelcow x50',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Widelcow x50',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Nozy x50',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Nozy x50',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Nozy x50',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿ek x50',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿ek x50',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿ek x50',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿eczek x50',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿eczek x50',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿eczek x50',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Talerzy x50',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Talerzy x50',6);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Talerzy x50',6);
--LOKAL7
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 1osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 2osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 3osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Stolik 4osobowy',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Piec kamienny PIECEX',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Piec kamienny PIECEX',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Patelnia TEFAL',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Patelnia TEFAL',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Kwiaty',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Widelcow x50',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Widelcow x50',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Widelcow x50',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Nozy x50',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Nozy x50',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Nozy x50',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿ek x50',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿ek x50',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿ek x50',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿eczek x50',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿eczek x50',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka £y¿eczek x50',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Talerzy x50',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Talerzy x50',7);
INSERT INTO WYPOSAZENIE VALUES (SEQ_WYPOSAZENIE.NEXTVAL,'Paczka Talerzy x50',7);
--ILOSC DANYCH: 546







--------------------------------FUNKCJE

--FUNKCJA_ID_LOKALU
CREATE OR REPLACE FUNCTION FUNKCJA_ID_LOKALU RETURN NUMERIC AS 
v_min NUMERIC;
v_max NUMERIC;
BEGIN
select min(ID_LOKALU), max(ID_LOKALU) 
into v_min, v_max
from LOKAL;
RETURN round(dbms_random.value(v_min,v_max),0);
END FUNKCJA_ID_LOKALU;
/





--FUNKCJA_ID_KLIENTA
create or replace FUNCTION FUNKCJA_ID_KLIENTA RETURN NUMERIC AS 
v_min NUMERIC;
v_max NUMERIC;
BEGIN
select min(ID_KLIENTA), max(ID_KLIENTA) 
into v_min, v_max
from KLIENT;
RETURN round(dbms_random.value(v_min,v_max),0);
END FUNKCJA_ID_KLIENTA;
/






--FUNKCJA_ID_SAMOCHODU
create or replace FUNCTION FUNKCJA_ID_SAMOCHODU 
(
lokal number,
klient number
)RETURN NUMERIC AS 
v_min NUMERIC;
v_max NUMERIC;
v_adres VARCHAR(500);
v_losowanie NUMERIC;
BEGIN

SELECT KLIENT.ADRES
into v_adres
FROM KLIENT
WHERE KLIENT.ID_KLIENTA=klient;

if v_adres IS NULL THEN
RETURN NULL;

ELSE
select min(SAMOCHOD.ID_SAMOCHODU), max(SAMOCHOD.ID_SAMOCHODU)
into v_min, v_max
from SAMOCHOD
where SAMOCHOD.ID_LOKALU=lokal;
RETURN round(dbms_random.value(v_min,v_max),0);

END IF;
END FUNKCJA_ID_SAMOCHODU;
/





--FUNKCJA_ID_PRODUKTU
create or replace FUNCTION FUNKCJA_ID_PRODUKTU
(
lokal number
)RETURN NUMBER AS 
v_min NUMERIC;
v_max NUMERIC;
BEGIN
select min(ID_PRODUKTU), max(ID_PRODUKTU) 
into v_min, v_max
from PRODUKT
where ID_LOKALU=lokal;
RETURN round(dbms_random.value(v_min,v_max),0);
END FUNKCJA_ID_PRODUKTU;
/





--FUNKCJA_ID_PRACOWNIKA
create or replace FUNCTION FUNKCJA_ID_PRACOWNIKA
(
lokal number
)RETURN NUMERIC AS 
v_min NUMERIC;
v_max NUMERIC;
BEGIN
select min(ID_PRACOWNIKA), max(ID_PRACOWNIKA) 
into v_min, v_max
from PRACOWNIK
WHERE ID_LOKALU=lokal;
RETURN round(dbms_random.value(v_min,v_max),0);
END FUNKCJA_ID_PRACOWNIKA;
/




--FUNKCJA_ID_PLATNOSCI
create or replace FUNCTION FUNKCJA_ID_PLATNOSCI RETURN NUMERIC AS 
v_min NUMERIC;
v_max NUMERIC;
BEGIN
select min(ID_PLATNOSCI), max(ID_PLATNOSCI) 
into v_min, v_max
from SPOSOB_PLATNOSCI;
RETURN round(dbms_random.value(v_min,v_max),0);
END FUNKCJA_ID_PLATNOSCI;
/



--FUNKCJA_CENA_ZAKUPU
create or replace FUNCTION FUNKCJA_CENA_ZAKUPU
(
product  float
)RETURN NUMBER AS 
v_cena float;
v_cena_ostateczna float;
BEGIN

select CENA_PRODUKTU 
into v_cena 
from PRODUKT
where id_produktu=product;
v_cena_ostateczna := v_cena*0.23+v_cena;
  RETURN v_cena_ostateczna;
END FUNKCJA_CENA_ZAKUPU;
/
-------------------------


------------------TRIGGERY

--TRIGGER DOLICZAJACY 5zl ZA DOWOZ
create or replace TRIGGER DOLICZENIE_DOWOZU
BEFORE INSERT 
ON FAKTURA_NAGLOWEK
FOR EACH ROW

BEGIN 

IF :new.ID_SAMOCHODU IS NOT NULL THEN
:new.WARTOSC_FAKTURY := 5;

END IF;
END;
/


----------------------------





--TWORZENIE PROCEDURY GENERUJACEJ TRANSAKCJE(1 DANA DO FAKTURA_NAGLOWEK, LOSOWA ILOSC DO FAKTURA_DETALE)
create or replace PROCEDURE GENEROWANIE_SPRZEDAZY( v_przychodzaca date ) AS
v_id_klienta numeric;
v_id_lokalu numeric;
v_id_samochodu numeric;
v_cena_zakupu numeric;
v_id_produktu numeric;
v_id_pracownika numeric;
v_id_platnosci numeric;
v_id_faktury numeric;
--ID do aktualizacji FAKTURA_NAGLOWEK.WARTOSC_FAKTURY
v_seq numeric;
--TERAZNIEJSZA DATA
v_data date;
--Generuje losowa liczbe kupionych produktow
v_liczba numeric;
--Losuje liczbe do petli wstawiania danych do FAKTURA_DETALE
v_generator numeric;
--Zmienna zapewniajaca odmiennosc kupionych produtkow
v_petla numeric;
BEGIN 
v_id_lokalu := FUNKCJA_ID_LOKALU;
v_id_klienta  := FUNKCJA_ID_KLIENTA;
v_id_samochodu := FUNKCJA_ID_SAMOCHODU(v_id_lokalu,v_id_klienta);
v_id_pracownika := FUNKCJA_ID_PRACOWNIKA(v_id_lokalu);
v_id_platnosci := FUNKCJA_ID_PLATNOSCI;




SELECT to_date(v_przychodzaca, 'DD/MM/YYYY')
into v_data
FROM DUAL;


--WSTAWIANIE ZAMOWIENIA KLIENTA
INSERT INTO FAKTURA_NAGLOWEK VALUES (SEQ_FAKTURA_NAGLOWEK.NEXTVAL,v_data,0,v_id_klienta,v_id_lokalu,v_id_samochodu,v_id_platnosci,v_id_pracownika);

--WSTAWIANIE DETALI ZAMOWIENIA KLIENTA
v_generator := dbms_random.value(1,5);
for v_petla in 1..v_generator
LOOP

v_id_produktu := FUNKCJA_ID_PRODUKTU(v_id_lokalu);
v_liczba := round(dbms_random.value(1,5),0);


--
INSERT INTO FAKTURA_DETALE VALUES (v_petla,SEQ_FAKTURA_NAGLOWEK.CURRVAL,v_liczba,FUNKCJA_CENA_ZAKUPU(v_id_produktu),v_id_produktu);
--

END LOOP;


--WYSZUKIWANIE AKTUALNEGO ID FAKTURY
SELECT SEQ_FAKTURA_NAGLOWEK.CURRVAL 
into v_seq
FROM DUAL;

--ZAAKTUALIZOWANIE WARTOSCI_FAKTURY
UPDATE FAKTURA_NAGLOWEK
SET FAKTURA_NAGLOWEK.WARTOSC_FAKTURY = FAKTURA_NAGLOWEK.WARTOSC_FAKTURY + (SELECT SUM(CENA_ZAKUPU * LICZBA)
FROM FAKTURA_DETALE
WHERE ID_FAKTURY = v_seq)
WHERE FAKTURA_NAGLOWEK.ID_FAKTURY=v_seq;

commit;

END GENEROWANIE_SPRZEDAZY;
/


--------------------GENEROWANIE DANYCH
BEGIN 



GENEROWANIE_SPRZEDAZY(date '2016-12-01');
GENEROWANIE_SPRZEDAZY(date '2016-12-02');
GENEROWANIE_SPRZEDAZY(date '2016-12-03');
GENEROWANIE_SPRZEDAZY(date '2016-12-04');
GENEROWANIE_SPRZEDAZY(date '2016-12-05');
GENEROWANIE_SPRZEDAZY(date '2016-12-06');
GENEROWANIE_SPRZEDAZY(date '2016-12-07');
GENEROWANIE_SPRZEDAZY(date '2016-12-08');
GENEROWANIE_SPRZEDAZY(date '2016-12-09');
GENEROWANIE_SPRZEDAZY(date '2016-12-10');
GENEROWANIE_SPRZEDAZY(date '2016-12-11');
GENEROWANIE_SPRZEDAZY(date '2016-12-12');
GENEROWANIE_SPRZEDAZY(date '2016-12-13');
GENEROWANIE_SPRZEDAZY(date '2016-12-14');
GENEROWANIE_SPRZEDAZY(date '2016-12-15');
GENEROWANIE_SPRZEDAZY(date '2016-12-16');
GENEROWANIE_SPRZEDAZY(date '2016-12-17');
GENEROWANIE_SPRZEDAZY(date '2016-12-18');
GENEROWANIE_SPRZEDAZY(date '2016-12-19');
GENEROWANIE_SPRZEDAZY(date '2016-12-20');
GENEROWANIE_SPRZEDAZY(date '2016-12-21');
GENEROWANIE_SPRZEDAZY(date '2016-12-22');
GENEROWANIE_SPRZEDAZY(date '2016-12-23');
GENEROWANIE_SPRZEDAZY(date '2016-12-24');
GENEROWANIE_SPRZEDAZY(date '2016-12-25');
GENEROWANIE_SPRZEDAZY(date '2016-12-26');
GENEROWANIE_SPRZEDAZY(date '2016-12-27');
GENEROWANIE_SPRZEDAZY(date '2016-12-28');
GENEROWANIE_SPRZEDAZY(date '2016-12-29');
GENEROWANIE_SPRZEDAZY(date '2016-12-30');
GENEROWANIE_SPRZEDAZY(date '2016-12-31');
GENEROWANIE_SPRZEDAZY(date '2017-01-01');
GENEROWANIE_SPRZEDAZY(date '2017-01-02');
GENEROWANIE_SPRZEDAZY(date '2017-01-03');
GENEROWANIE_SPRZEDAZY(date '2017-01-04');
GENEROWANIE_SPRZEDAZY(date '2017-01-05');
GENEROWANIE_SPRZEDAZY(date '2017-01-06');
GENEROWANIE_SPRZEDAZY(date '2017-01-07');
GENEROWANIE_SPRZEDAZY(date '2017-01-08');
GENEROWANIE_SPRZEDAZY(date '2017-01-09');
GENEROWANIE_SPRZEDAZY(date '2017-01-10');
GENEROWANIE_SPRZEDAZY(date '2017-01-11');
GENEROWANIE_SPRZEDAZY(date '2017-01-12');
GENEROWANIE_SPRZEDAZY(date '2017-01-13');
GENEROWANIE_SPRZEDAZY(date '2017-01-14');
GENEROWANIE_SPRZEDAZY(date '2017-01-15');
GENEROWANIE_SPRZEDAZY(date '2017-01-16');
GENEROWANIE_SPRZEDAZY(date '2017-01-17');
GENEROWANIE_SPRZEDAZY(date '2017-01-18');
GENEROWANIE_SPRZEDAZY(date '2017-01-19');
GENEROWANIE_SPRZEDAZY(date '2017-01-20');
GENEROWANIE_SPRZEDAZY(date '2017-01-21');
GENEROWANIE_SPRZEDAZY(date '2017-01-22');
GENEROWANIE_SPRZEDAZY(date '2017-01-23');
GENEROWANIE_SPRZEDAZY(date '2017-01-24');
GENEROWANIE_SPRZEDAZY(date '2017-01-25');
GENEROWANIE_SPRZEDAZY(date '2017-01-26');
GENEROWANIE_SPRZEDAZY(date '2017-01-27');
GENEROWANIE_SPRZEDAZY(date '2017-01-28');
GENEROWANIE_SPRZEDAZY(date '2017-01-29');
GENEROWANIE_SPRZEDAZY(date '2017-01-30');
GENEROWANIE_SPRZEDAZY(date '2017-01-31');
GENEROWANIE_SPRZEDAZY(date '2017-02-01');
GENEROWANIE_SPRZEDAZY(date '2017-02-02');
GENEROWANIE_SPRZEDAZY(date '2017-02-03');
GENEROWANIE_SPRZEDAZY(date '2017-02-04');
GENEROWANIE_SPRZEDAZY(date '2017-02-05');
GENEROWANIE_SPRZEDAZY(date '2017-02-06');
GENEROWANIE_SPRZEDAZY(date '2017-02-07');
GENEROWANIE_SPRZEDAZY(date '2017-02-08');
GENEROWANIE_SPRZEDAZY(date '2017-02-09');
GENEROWANIE_SPRZEDAZY(date '2017-02-10');
GENEROWANIE_SPRZEDAZY(date '2017-02-11');
GENEROWANIE_SPRZEDAZY(date '2017-02-12');
GENEROWANIE_SPRZEDAZY(date '2017-02-13');
GENEROWANIE_SPRZEDAZY(date '2017-02-14');
GENEROWANIE_SPRZEDAZY(date '2017-02-15');
GENEROWANIE_SPRZEDAZY(date '2017-02-16');
GENEROWANIE_SPRZEDAZY(date '2017-02-17');
GENEROWANIE_SPRZEDAZY(date '2017-02-18');
GENEROWANIE_SPRZEDAZY(date '2017-02-19');
GENEROWANIE_SPRZEDAZY(date '2017-02-20');
GENEROWANIE_SPRZEDAZY(date '2017-02-21');
GENEROWANIE_SPRZEDAZY(date '2017-02-22');
GENEROWANIE_SPRZEDAZY(date '2017-02-23');
GENEROWANIE_SPRZEDAZY(date '2017-02-24');
GENEROWANIE_SPRZEDAZY(date '2017-02-25');
GENEROWANIE_SPRZEDAZY(date '2017-02-26');
GENEROWANIE_SPRZEDAZY(date '2017-02-27');
GENEROWANIE_SPRZEDAZY(date '2017-02-28');
GENEROWANIE_SPRZEDAZY(date '2017-03-01');
GENEROWANIE_SPRZEDAZY(date '2017-03-02');
GENEROWANIE_SPRZEDAZY(date '2017-03-03');
GENEROWANIE_SPRZEDAZY(date '2017-03-04');
GENEROWANIE_SPRZEDAZY(date '2017-03-05');
GENEROWANIE_SPRZEDAZY(date '2017-03-06');
GENEROWANIE_SPRZEDAZY(date '2017-03-07');
GENEROWANIE_SPRZEDAZY(date '2017-03-08');
GENEROWANIE_SPRZEDAZY(date '2017-03-09');
GENEROWANIE_SPRZEDAZY(date '2017-03-10');
GENEROWANIE_SPRZEDAZY(date '2017-03-11');
GENEROWANIE_SPRZEDAZY(date '2017-03-12');
GENEROWANIE_SPRZEDAZY(date '2017-03-13');
GENEROWANIE_SPRZEDAZY(date '2017-03-14');
GENEROWANIE_SPRZEDAZY(date '2017-03-15');
GENEROWANIE_SPRZEDAZY(date '2017-03-16');
GENEROWANIE_SPRZEDAZY(date '2017-03-17');
GENEROWANIE_SPRZEDAZY(date '2017-03-18');
GENEROWANIE_SPRZEDAZY(date '2017-03-19');
GENEROWANIE_SPRZEDAZY(date '2017-03-20');
GENEROWANIE_SPRZEDAZY(date '2017-03-21');
GENEROWANIE_SPRZEDAZY(date '2017-03-22');
GENEROWANIE_SPRZEDAZY(date '2017-03-23');
GENEROWANIE_SPRZEDAZY(date '2017-03-24');
GENEROWANIE_SPRZEDAZY(date '2017-03-25');
GENEROWANIE_SPRZEDAZY(date '2017-03-26');
GENEROWANIE_SPRZEDAZY(date '2017-03-27');
GENEROWANIE_SPRZEDAZY(date '2017-03-28');
GENEROWANIE_SPRZEDAZY(date '2017-03-29');
GENEROWANIE_SPRZEDAZY(date '2017-03-30');
GENEROWANIE_SPRZEDAZY(date '2017-03-31');
GENEROWANIE_SPRZEDAZY(date '2017-04-01');
GENEROWANIE_SPRZEDAZY(date '2017-04-02');
GENEROWANIE_SPRZEDAZY(date '2017-04-03');
GENEROWANIE_SPRZEDAZY(date '2017-04-04');
GENEROWANIE_SPRZEDAZY(date '2017-04-05');
GENEROWANIE_SPRZEDAZY(date '2017-04-06');
GENEROWANIE_SPRZEDAZY(date '2017-04-07');
GENEROWANIE_SPRZEDAZY(date '2017-04-08');
GENEROWANIE_SPRZEDAZY(date '2017-04-09');
GENEROWANIE_SPRZEDAZY(date '2017-04-10');
GENEROWANIE_SPRZEDAZY(date '2017-04-11');
GENEROWANIE_SPRZEDAZY(date '2017-04-12');
GENEROWANIE_SPRZEDAZY(date '2017-04-13');
GENEROWANIE_SPRZEDAZY(date '2017-04-14');
GENEROWANIE_SPRZEDAZY(date '2017-04-15');
GENEROWANIE_SPRZEDAZY(date '2017-04-16');
GENEROWANIE_SPRZEDAZY(date '2017-04-17');
GENEROWANIE_SPRZEDAZY(date '2017-04-18');
GENEROWANIE_SPRZEDAZY(date '2017-04-19');
GENEROWANIE_SPRZEDAZY(date '2017-04-20');
GENEROWANIE_SPRZEDAZY(date '2017-04-21');
GENEROWANIE_SPRZEDAZY(date '2017-04-22');
GENEROWANIE_SPRZEDAZY(date '2017-04-23');
GENEROWANIE_SPRZEDAZY(date '2017-04-24');
GENEROWANIE_SPRZEDAZY(date '2017-04-25');
GENEROWANIE_SPRZEDAZY(date '2017-04-26');
GENEROWANIE_SPRZEDAZY(date '2017-04-27');
GENEROWANIE_SPRZEDAZY(date '2017-04-28');
GENEROWANIE_SPRZEDAZY(date '2017-04-29');
GENEROWANIE_SPRZEDAZY(date '2017-04-30');
GENEROWANIE_SPRZEDAZY(date '2017-05-01');
GENEROWANIE_SPRZEDAZY(date '2017-05-02');
GENEROWANIE_SPRZEDAZY(date '2017-05-03');
GENEROWANIE_SPRZEDAZY(date '2017-05-04');
GENEROWANIE_SPRZEDAZY(date '2017-05-05');
GENEROWANIE_SPRZEDAZY(date '2017-05-06');
GENEROWANIE_SPRZEDAZY(date '2017-05-07');
GENEROWANIE_SPRZEDAZY(date '2017-05-08');
GENEROWANIE_SPRZEDAZY(date '2017-05-09');
GENEROWANIE_SPRZEDAZY(date '2017-05-10');
GENEROWANIE_SPRZEDAZY(date '2017-05-11');
GENEROWANIE_SPRZEDAZY(date '2017-05-12');
GENEROWANIE_SPRZEDAZY(date '2017-05-13');
GENEROWANIE_SPRZEDAZY(date '2017-05-14');
GENEROWANIE_SPRZEDAZY(date '2017-05-15');
GENEROWANIE_SPRZEDAZY(date '2017-05-16');
GENEROWANIE_SPRZEDAZY(date '2017-05-17');
GENEROWANIE_SPRZEDAZY(date '2017-05-18');
GENEROWANIE_SPRZEDAZY(date '2017-05-19');
GENEROWANIE_SPRZEDAZY(date '2017-05-20');
GENEROWANIE_SPRZEDAZY(date '2017-05-21');
GENEROWANIE_SPRZEDAZY(date '2017-05-22');
GENEROWANIE_SPRZEDAZY(date '2017-05-23');
GENEROWANIE_SPRZEDAZY(date '2017-05-24');
GENEROWANIE_SPRZEDAZY(date '2017-05-25');
GENEROWANIE_SPRZEDAZY(date '2017-05-26');
GENEROWANIE_SPRZEDAZY(date '2017-05-27');
GENEROWANIE_SPRZEDAZY(date '2017-05-28');
GENEROWANIE_SPRZEDAZY(date '2017-05-29');
GENEROWANIE_SPRZEDAZY(date '2017-05-30');
GENEROWANIE_SPRZEDAZY(date '2017-05-31');
GENEROWANIE_SPRZEDAZY(date '2017-06-01');
GENEROWANIE_SPRZEDAZY(date '2017-06-02');
GENEROWANIE_SPRZEDAZY(date '2017-06-03');
GENEROWANIE_SPRZEDAZY(date '2017-06-04');
GENEROWANIE_SPRZEDAZY(date '2017-06-05');
GENEROWANIE_SPRZEDAZY(date '2017-06-06');
GENEROWANIE_SPRZEDAZY(date '2017-06-07');
GENEROWANIE_SPRZEDAZY(date '2017-06-08');
GENEROWANIE_SPRZEDAZY(date '2017-06-09');
GENEROWANIE_SPRZEDAZY(date '2017-06-10');
GENEROWANIE_SPRZEDAZY(date '2017-06-11');
GENEROWANIE_SPRZEDAZY(date '2017-06-12');
GENEROWANIE_SPRZEDAZY(date '2017-06-13');
GENEROWANIE_SPRZEDAZY(date '2017-06-14');
GENEROWANIE_SPRZEDAZY(date '2017-06-15');
GENEROWANIE_SPRZEDAZY(date '2017-06-16');
GENEROWANIE_SPRZEDAZY(date '2017-06-17');
GENEROWANIE_SPRZEDAZY(date '2017-06-18');
GENEROWANIE_SPRZEDAZY(date '2017-06-19');
GENEROWANIE_SPRZEDAZY(date '2017-06-20');
GENEROWANIE_SPRZEDAZY(date '2017-06-21');
GENEROWANIE_SPRZEDAZY(date '2017-06-22');
GENEROWANIE_SPRZEDAZY(date '2017-06-23');
GENEROWANIE_SPRZEDAZY(date '2017-06-24');
GENEROWANIE_SPRZEDAZY(date '2017-06-25');
GENEROWANIE_SPRZEDAZY(date '2017-06-26');
GENEROWANIE_SPRZEDAZY(date '2017-06-27');
GENEROWANIE_SPRZEDAZY(date '2017-06-28');
GENEROWANIE_SPRZEDAZY(date '2017-06-29');
GENEROWANIE_SPRZEDAZY(date '2017-06-30');
GENEROWANIE_SPRZEDAZY(date '2017-07-01');
GENEROWANIE_SPRZEDAZY(date '2017-07-02');
GENEROWANIE_SPRZEDAZY(date '2017-07-03');
GENEROWANIE_SPRZEDAZY(date '2017-07-04');
GENEROWANIE_SPRZEDAZY(date '2017-07-05');
GENEROWANIE_SPRZEDAZY(date '2017-07-06');
GENEROWANIE_SPRZEDAZY(date '2017-07-07');
GENEROWANIE_SPRZEDAZY(date '2017-07-08');
GENEROWANIE_SPRZEDAZY(date '2017-07-09');
GENEROWANIE_SPRZEDAZY(date '2017-07-10');
GENEROWANIE_SPRZEDAZY(date '2017-07-11');
GENEROWANIE_SPRZEDAZY(date '2017-07-12');
GENEROWANIE_SPRZEDAZY(date '2017-07-13');
GENEROWANIE_SPRZEDAZY(date '2017-07-14');
GENEROWANIE_SPRZEDAZY(date '2017-07-15');
GENEROWANIE_SPRZEDAZY(date '2017-07-16');
GENEROWANIE_SPRZEDAZY(date '2017-07-17');
GENEROWANIE_SPRZEDAZY(date '2017-07-18');
GENEROWANIE_SPRZEDAZY(date '2017-07-19');
GENEROWANIE_SPRZEDAZY(date '2017-07-20');
GENEROWANIE_SPRZEDAZY(date '2017-07-21');
GENEROWANIE_SPRZEDAZY(date '2017-07-22');
GENEROWANIE_SPRZEDAZY(date '2017-07-23');
GENEROWANIE_SPRZEDAZY(date '2017-07-24');
GENEROWANIE_SPRZEDAZY(date '2017-07-25');
GENEROWANIE_SPRZEDAZY(date '2017-07-26');
GENEROWANIE_SPRZEDAZY(date '2017-07-27');
GENEROWANIE_SPRZEDAZY(date '2017-07-28');
GENEROWANIE_SPRZEDAZY(date '2017-07-29');
GENEROWANIE_SPRZEDAZY(date '2017-07-30');
GENEROWANIE_SPRZEDAZY(date '2017-07-31');
GENEROWANIE_SPRZEDAZY(date '2017-08-01');
GENEROWANIE_SPRZEDAZY(date '2017-08-02');
GENEROWANIE_SPRZEDAZY(date '2017-08-03');
GENEROWANIE_SPRZEDAZY(date '2017-08-04');
GENEROWANIE_SPRZEDAZY(date '2017-08-05');
GENEROWANIE_SPRZEDAZY(date '2017-08-06');
GENEROWANIE_SPRZEDAZY(date '2017-08-07');
GENEROWANIE_SPRZEDAZY(date '2017-08-08');
GENEROWANIE_SPRZEDAZY(date '2017-08-09');
GENEROWANIE_SPRZEDAZY(date '2017-08-10');
GENEROWANIE_SPRZEDAZY(date '2017-08-11');
GENEROWANIE_SPRZEDAZY(date '2017-08-12');
GENEROWANIE_SPRZEDAZY(date '2017-08-13');
GENEROWANIE_SPRZEDAZY(date '2017-08-14');
GENEROWANIE_SPRZEDAZY(date '2017-08-15');
GENEROWANIE_SPRZEDAZY(date '2017-08-16');
GENEROWANIE_SPRZEDAZY(date '2017-08-17');
GENEROWANIE_SPRZEDAZY(date '2017-08-18');
GENEROWANIE_SPRZEDAZY(date '2017-08-19');
GENEROWANIE_SPRZEDAZY(date '2017-08-20');
GENEROWANIE_SPRZEDAZY(date '2017-08-21');
GENEROWANIE_SPRZEDAZY(date '2017-08-22');
GENEROWANIE_SPRZEDAZY(date '2017-08-23');
GENEROWANIE_SPRZEDAZY(date '2017-08-24');
GENEROWANIE_SPRZEDAZY(date '2017-08-25');
GENEROWANIE_SPRZEDAZY(date '2017-08-26');
GENEROWANIE_SPRZEDAZY(date '2017-08-27');
GENEROWANIE_SPRZEDAZY(date '2017-08-28');
GENEROWANIE_SPRZEDAZY(date '2017-08-29');
GENEROWANIE_SPRZEDAZY(date '2017-08-30');
GENEROWANIE_SPRZEDAZY(date '2017-08-31');
GENEROWANIE_SPRZEDAZY(date '2017-09-01');
GENEROWANIE_SPRZEDAZY(date '2017-09-02');
GENEROWANIE_SPRZEDAZY(date '2017-09-03');
GENEROWANIE_SPRZEDAZY(date '2017-09-04');
GENEROWANIE_SPRZEDAZY(date '2017-09-05');
GENEROWANIE_SPRZEDAZY(date '2017-09-06');
GENEROWANIE_SPRZEDAZY(date '2017-09-07');
GENEROWANIE_SPRZEDAZY(date '2017-09-08');
GENEROWANIE_SPRZEDAZY(date '2017-09-09');
GENEROWANIE_SPRZEDAZY(date '2017-09-10');
GENEROWANIE_SPRZEDAZY(date '2017-09-11');
GENEROWANIE_SPRZEDAZY(date '2017-09-12');
GENEROWANIE_SPRZEDAZY(date '2017-09-13');
GENEROWANIE_SPRZEDAZY(date '2017-09-14');
GENEROWANIE_SPRZEDAZY(date '2017-09-15');
GENEROWANIE_SPRZEDAZY(date '2017-09-16');
GENEROWANIE_SPRZEDAZY(date '2017-09-17');
GENEROWANIE_SPRZEDAZY(date '2017-09-18');
GENEROWANIE_SPRZEDAZY(date '2017-09-19');
GENEROWANIE_SPRZEDAZY(date '2017-09-20');
GENEROWANIE_SPRZEDAZY(date '2017-09-21');
GENEROWANIE_SPRZEDAZY(date '2017-09-22');
GENEROWANIE_SPRZEDAZY(date '2017-09-23');
GENEROWANIE_SPRZEDAZY(date '2017-09-24');
GENEROWANIE_SPRZEDAZY(date '2017-09-25');
GENEROWANIE_SPRZEDAZY(date '2017-09-26');
GENEROWANIE_SPRZEDAZY(date '2017-09-27');
GENEROWANIE_SPRZEDAZY(date '2017-09-28');
GENEROWANIE_SPRZEDAZY(date '2017-09-29');
GENEROWANIE_SPRZEDAZY(date '2017-09-30');
GENEROWANIE_SPRZEDAZY(date '2017-10-01');
GENEROWANIE_SPRZEDAZY(date '2017-10-02');
GENEROWANIE_SPRZEDAZY(date '2017-10-03');
GENEROWANIE_SPRZEDAZY(date '2017-10-04');
GENEROWANIE_SPRZEDAZY(date '2017-10-05');
GENEROWANIE_SPRZEDAZY(date '2017-10-06');
GENEROWANIE_SPRZEDAZY(date '2017-10-07');
GENEROWANIE_SPRZEDAZY(date '2017-10-08');
GENEROWANIE_SPRZEDAZY(date '2017-10-09');
GENEROWANIE_SPRZEDAZY(date '2017-10-10');
GENEROWANIE_SPRZEDAZY(date '2017-10-11');
GENEROWANIE_SPRZEDAZY(date '2017-10-12');
GENEROWANIE_SPRZEDAZY(date '2017-10-13');
GENEROWANIE_SPRZEDAZY(date '2017-10-14');
GENEROWANIE_SPRZEDAZY(date '2017-10-15');
GENEROWANIE_SPRZEDAZY(date '2017-10-16');
GENEROWANIE_SPRZEDAZY(date '2017-10-17');
GENEROWANIE_SPRZEDAZY(date '2017-10-18');
GENEROWANIE_SPRZEDAZY(date '2017-10-19');
GENEROWANIE_SPRZEDAZY(date '2017-10-20');
GENEROWANIE_SPRZEDAZY(date '2017-10-21');
GENEROWANIE_SPRZEDAZY(date '2017-10-22');
GENEROWANIE_SPRZEDAZY(date '2017-10-23');
GENEROWANIE_SPRZEDAZY(date '2017-10-24');
GENEROWANIE_SPRZEDAZY(date '2017-10-25');
GENEROWANIE_SPRZEDAZY(date '2017-10-26');
GENEROWANIE_SPRZEDAZY(date '2017-10-27');
GENEROWANIE_SPRZEDAZY(date '2017-10-28');
GENEROWANIE_SPRZEDAZY(date '2017-10-29');
GENEROWANIE_SPRZEDAZY(date '2017-10-30');
GENEROWANIE_SPRZEDAZY(date '2017-10-31');
GENEROWANIE_SPRZEDAZY(date '2017-11-01');
GENEROWANIE_SPRZEDAZY(date '2017-11-02');
GENEROWANIE_SPRZEDAZY(date '2017-11-03');
GENEROWANIE_SPRZEDAZY(date '2017-11-04');
GENEROWANIE_SPRZEDAZY(date '2017-11-05');
GENEROWANIE_SPRZEDAZY(date '2017-11-06');
GENEROWANIE_SPRZEDAZY(date '2017-11-07');
GENEROWANIE_SPRZEDAZY(date '2017-11-08');
GENEROWANIE_SPRZEDAZY(date '2017-11-09');
GENEROWANIE_SPRZEDAZY(date '2017-11-10');
GENEROWANIE_SPRZEDAZY(date '2017-11-11');
GENEROWANIE_SPRZEDAZY(date '2017-11-12');
GENEROWANIE_SPRZEDAZY(date '2017-11-13');
GENEROWANIE_SPRZEDAZY(date '2017-11-14');
GENEROWANIE_SPRZEDAZY(date '2017-11-15');
GENEROWANIE_SPRZEDAZY(date '2017-11-16');
GENEROWANIE_SPRZEDAZY(date '2017-11-17');
GENEROWANIE_SPRZEDAZY(date '2017-11-18');
GENEROWANIE_SPRZEDAZY(date '2017-11-19');
GENEROWANIE_SPRZEDAZY(date '2017-11-20');
GENEROWANIE_SPRZEDAZY(date '2017-11-21');
GENEROWANIE_SPRZEDAZY(date '2017-11-22');
GENEROWANIE_SPRZEDAZY(date '2017-11-23');
GENEROWANIE_SPRZEDAZY(date '2017-11-24');
GENEROWANIE_SPRZEDAZY(date '2017-11-25');
GENEROWANIE_SPRZEDAZY(date '2017-11-26');
GENEROWANIE_SPRZEDAZY(date '2017-11-27');
GENEROWANIE_SPRZEDAZY(date '2017-11-28');
GENEROWANIE_SPRZEDAZY(date '2017-11-29');
GENEROWANIE_SPRZEDAZY(date '2017-11-30');
GENEROWANIE_SPRZEDAZY(date '2017-12-01');
GENEROWANIE_SPRZEDAZY(date '2017-12-02');
GENEROWANIE_SPRZEDAZY(date '2017-12-03');
GENEROWANIE_SPRZEDAZY(date '2017-12-04');
GENEROWANIE_SPRZEDAZY(date '2017-12-05');
GENEROWANIE_SPRZEDAZY(date '2017-12-06');
GENEROWANIE_SPRZEDAZY(date '2017-12-07');
GENEROWANIE_SPRZEDAZY(date '2017-12-08');
GENEROWANIE_SPRZEDAZY(date '2017-12-09');
GENEROWANIE_SPRZEDAZY(date '2017-12-10');
GENEROWANIE_SPRZEDAZY(date '2017-12-11');
GENEROWANIE_SPRZEDAZY(date '2017-12-12');
GENEROWANIE_SPRZEDAZY(date '2017-12-13');
GENEROWANIE_SPRZEDAZY(date '2017-12-14');
GENEROWANIE_SPRZEDAZY(date '2017-12-15');
GENEROWANIE_SPRZEDAZY(date '2017-12-16');
GENEROWANIE_SPRZEDAZY(date '2017-12-17');
GENEROWANIE_SPRZEDAZY(date '2017-12-18');
GENEROWANIE_SPRZEDAZY(date '2017-12-19');
GENEROWANIE_SPRZEDAZY(date '2017-12-20');
GENEROWANIE_SPRZEDAZY(date '2017-12-21');
GENEROWANIE_SPRZEDAZY(date '2017-12-22');
GENEROWANIE_SPRZEDAZY(date '2017-12-23');
GENEROWANIE_SPRZEDAZY(date '2017-12-24');
GENEROWANIE_SPRZEDAZY(date '2017-12-25');
GENEROWANIE_SPRZEDAZY(date '2017-12-26');
GENEROWANIE_SPRZEDAZY(date '2017-12-27');
GENEROWANIE_SPRZEDAZY(date '2017-12-28');
GENEROWANIE_SPRZEDAZY(date '2017-12-29');
GENEROWANIE_SPRZEDAZY(date '2017-12-30');
GENEROWANIE_SPRZEDAZY(date '2017-12-31');
GENEROWANIE_SPRZEDAZY(date '2018-01-01');
GENEROWANIE_SPRZEDAZY(date '2018-01-02');
GENEROWANIE_SPRZEDAZY(date '2018-01-03');
GENEROWANIE_SPRZEDAZY(date '2018-01-04');
GENEROWANIE_SPRZEDAZY(date '2018-01-05');
GENEROWANIE_SPRZEDAZY(date '2018-01-06');
GENEROWANIE_SPRZEDAZY(date '2018-01-07');
GENEROWANIE_SPRZEDAZY(date '2018-01-08');
GENEROWANIE_SPRZEDAZY(date '2018-01-09');
GENEROWANIE_SPRZEDAZY(date '2018-01-10');
GENEROWANIE_SPRZEDAZY(date '2018-01-11');
GENEROWANIE_SPRZEDAZY(date '2018-01-12');
GENEROWANIE_SPRZEDAZY(date '2018-01-13');
GENEROWANIE_SPRZEDAZY(date '2018-01-14');
GENEROWANIE_SPRZEDAZY(date '2018-01-15');
GENEROWANIE_SPRZEDAZY(date '2018-01-16');
GENEROWANIE_SPRZEDAZY(date '2018-01-17');
GENEROWANIE_SPRZEDAZY(date '2018-01-18');
GENEROWANIE_SPRZEDAZY(date '2018-01-19');
GENEROWANIE_SPRZEDAZY(date '2018-01-20');
GENEROWANIE_SPRZEDAZY(date '2018-01-20');
GENEROWANIE_SPRZEDAZY(date '2018-01-20');
GENEROWANIE_SPRZEDAZY(date '2018-01-20');
GENEROWANIE_SPRZEDAZY(date '2018-01-20');
GENEROWANIE_SPRZEDAZY(date '2018-01-20');
GENEROWANIE_SPRZEDAZY(date '2018-01-20');
GENEROWANIE_SPRZEDAZY(date '2018-01-20');
GENEROWANIE_SPRZEDAZY(date '2018-01-20');
GENEROWANIE_SPRZEDAZY(date '2018-01-20');
GENEROWANIE_SPRZEDAZY(date '2018-01-20');
GENEROWANIE_SPRZEDAZY(date '2018-01-20');
GENEROWANIE_SPRZEDAZY(date '2018-01-20');
GENEROWANIE_SPRZEDAZY(date '2018-01-20');
GENEROWANIE_SPRZEDAZY(date '2018-01-20');
GENEROWANIE_SPRZEDAZY(date '2018-01-20');
GENEROWANIE_SPRZEDAZY(date '2018-01-20');
GENEROWANIE_SPRZEDAZY(date '2018-01-20');
GENEROWANIE_SPRZEDAZY(date '2018-01-20');
GENEROWANIE_SPRZEDAZY(date '2018-01-20');
GENEROWANIE_SPRZEDAZY(date '2018-01-21');
GENEROWANIE_SPRZEDAZY(date '2018-01-22');
GENEROWANIE_SPRZEDAZY(date '2018-01-23');
GENEROWANIE_SPRZEDAZY(date '2018-01-24');
GENEROWANIE_SPRZEDAZY(date '2018-01-25');
GENEROWANIE_SPRZEDAZY(date '2018-01-26');
GENEROWANIE_SPRZEDAZY(sysdate);
GENEROWANIE_SPRZEDAZY(sysdate);
GENEROWANIE_SPRZEDAZY(sysdate);
GENEROWANIE_SPRZEDAZY(sysdate);
GENEROWANIE_SPRZEDAZY(sysdate);
GENEROWANIE_SPRZEDAZY(sysdate);
GENEROWANIE_SPRZEDAZY(sysdate);
GENEROWANIE_SPRZEDAZY(sysdate);
--FAKTURA_NAGLOWEK: 436 REKORDÓW

END;
/

-----------------------------------PERSPEKTYWY 


--PERSPEKTYWA ANALITYCZNA LOKALII
CREATE OR REPLACE VIEW LOKALE_SPRZEDAZ AS
SELECT LOKAL.ID_LOKALU AS "ID LOKALU",
 LOKAL.NAZWA_LOKALU AS "LOKAL",
 TO_CHAR(SUM(FAKTURA_NAGLOWEK.WARTOSC_FAKTURY / 1.23),'99000.00') AS "SPRZEDAZ BEZ PODATKU",
'23%' AS "PODATEK",
TO_CHAR(SUM(FAKTURA_NAGLOWEK.WARTOSC_FAKTURY), '99000.00') AS "SPRZEDAZ Z PODATKIEM",
LOKAL.KOSZT AS "KOSZT LOKALU",
TO_CHAR(SUM(FAKTURA_NAGLOWEK.WARTOSC_FAKTURY)  - LOKAL.KOSZT,'99000.00') AS "ZYSK"
FROM LOKAL JOIN FAKTURA_NAGLOWEK ON LOKAL.ID_LOKALU = FAKTURA_NAGLOWEK.ID_LOKALU
GROUP BY LOKAL.ID_LOKALU,LOKAL.NAZWA_LOKALU,LOKAL.KOSZT
ORDER BY LOKAL.ID_LOKALU;

--PERSPEKTYWA MENU LOKALU 1
CREATE OR REPLACE VIEW MENU_LOKAL_1 AS
SELECT PRODUKT.NAZWA_PRODUKTU AS "PRODUKT", TO_CHAR(PRODUKT.CENA_PRODUKTU*1.23,'00.00') AS "CENA"
FROM PRODUKT
WHERE ID_LOKALU = 1;

--PERSPEKTYWA SPIS PRACOWNIKOW LOKALU 1
CREATE OR REPLACE VIEW PRACOWNICY_LOKAL_1 AS
SELECT PRACOWNIK.ID_PRACOWNIKA AS "ID PRACOWNIKA", PRACOWNIK.IMIE, PRACOWNIK.NAZWISKO
FROM PRACOWNIK
WHERE PRACOWNIK.ID_LOKALU = 1;

--PERSPEKTYWA SAMOCHODY 
CREATE OR REPLACE VIEW SAMOCHODY AS 
SELECT LOKAL.NAZWA_LOKALU AS "LOKAL", SAMOCHOD.NAZWA_SAMOCHODU AS "SAMOCHOD"
FROM SAMOCHOD JOIN LOKAL ON SAMOCHOD.ID_LOKALU = LOKAL.ID_LOKALU;

--PERSPEKTYWA WYPOSAZENIE LOKALU 1
CREATE OR REPLACE VIEW WYPOSAZENIE_LOKAL_1 AS
SELECT ID_WYPOSAZENIA AS "ID", NAZWA_WYPOSAZENIA AS "WYPOSAZENIE" FROM WYPOSAZENIE
WHERE ID_LOKALU = 1;

--PERSPEKTYWA PARAGON KLIENTA 1
CREATE OR REPLACE VIEW PARAGON_KLIENT_1 AS
SELECT PRODUKT.NAZWA_PRODUKTU AS "PRODUKT",
FAKTURA_DETALE.LICZBA,
TO_CHAR(FAKTURA_DETALE.CENA_ZAKUPU/1.23,'00.00') AS "CENA",
'23%' AS "VAT",
TO_CHAR(FAKTURA_DETALE.LICZBA*FAKTURA_DETALE.CENA_ZAKUPU,'900.00') AS "CENA OSTATECZNA (Z VAT)"
FROM (FAKTURA_DETALE JOIN PRODUKT ON FAKTURA_DETALE.ID_PRODUKTU = PRODUKT.ID_PRODUKTU)
JOIN FAKTURA_NAGLOWEK ON FAKTURA_DETALE.ID_FAKTURY = FAKTURA_NAGLOWEK.ID_FAKTURY
WHERE FAKTURA_NAGLOWEK.ID_KLIENTA = 1;
